version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 0098
      POSTGRES_USER: postgres
      POSTGRES_DB: generator
  app:
    image: node-app
    #Mapping port number for the container
    ports:
      - 13000:3001
